version: "3.8"

services:
  # Backend
  backend-todo:
    container_name: backend-todo-container
    build:
      context: ./backend_todo
    ports:
      - "3001:3001"
    env_file:
      - ./backend_todo/.env
    volumes:
      - ./backend_todo/prisma:/app/prisma
    command: >
      sh -c "npx prisma migrate deploy && yarn start:prod"
    networks:
      - app-network

  # Frontend
  frontend-todo:
    container_name: frontend-todo-container
    build:
      context: ./frontend_todo
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      - backend-todo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
